"""Build a single-file concatenation of v7 for LLM analysis.

Usage:
  python tools/build_snapshot.py > v7_snapshot.py
  # Then paste v7_snapshot.py into ChatGPT/Claude.

Existing files stay untouched — this is a read-only export, not a refactor.
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

ORDER = [
    "lab/tape.py",
    "lab/sim.py",
    "lab/indicators.py",
    "lab/events.py",
    "lab/observe.py",
    "tools/snapshot.py",
    "tools/download_binance.py",
]

SEPARATOR = "\n" + "# " + "─" * 72 + "\n"


def main() -> None:
    parts: list[str] = [
        "# v7 — single-file snapshot for LLM analysis",
        f"# Generated by: python tools/build_snapshot.py",
        f"# Files: {len(ORDER)}",
        "#",
        "# lab/  — deterministic core (no network, no pyarrow, no wall-clock)",
        "# tools/ — data acquisition (network + parquet I/O, outside core)",
        "#",
        "# Paste this entire file into ChatGPT/Claude for cross-file analysis.",
        "",
    ]

    for rel in ORDER:
        path = ROOT / rel
        if not path.exists():
            print(f"WARNING: {rel} not found, skipping", file=sys.stderr)
            continue
        content = path.read_text(encoding="utf-8")
        # Strip __future__ imports and sys.path hacks (only needed in multi-file mode)
        lines = content.splitlines()
        filtered: list[str] = []
        skip_until_empty = False
        for line in lines:
            if line.startswith("from __future__"):
                continue
            if line.startswith("sys.path.insert"):
                skip_until_empty = True
                continue
            if skip_until_empty:
                if line.strip() == "":
                    skip_until_empty = False
                continue
            # Replace relative imports with comments
            if line.startswith("from lab import") or line.startswith("from tools import"):
                filtered.append(f"# [single-file: {line.strip()}]")
                continue
            if line.startswith("from lab.") or line.startswith("from tools."):
                filtered.append(f"# [single-file: {line.strip()}]")
                continue
            filtered.append(line)

        header = f"# ── {rel} ──"
        parts.append(SEPARATOR + header + "\n" + "\n".join(filtered))

    print("\n".join(parts))


if __name__ == "__main__":
    main()
